name: Pester Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        shell: pwsh

      - name: Run Pester tests with Code Coverage
        run: |
          $Coverage = Invoke-Pester ./tests -CI -Output Detailed -CodeCoverage ./NetzlaufwerkTools/NetzlaufwerkTools.psm1
          $Coverage.Coverage | Format-Table -AutoSize
        shell: pwsh
