name: Pester Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pester:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -Force -Scope CurrentUser

    - name: Run Pester Tests
      working-directory: ./solution
      run: |
        # Run Pester tests with Code Coverage
        $config = New-PesterConfiguration
        $config.Run.Path = "."
        $config.CodeCoverage.Enabled = $true
        $config.TestResult.Enabled = $true
        Invoke-Pester -Configuration $config

    - name: Upload code coverage report
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: solution\coverage.xml
